
USE DB_T04301_JESSE_ALVES;


CREATE TABLE TB_CONTATOS(
	 id_contato INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    telefone VARCHAR(20) NOT NULL
);

INSERT INTO TB_CONTATOS (nome, telefone)
VALUES ('FLAVIO', '(14) 98888-7777'),
       ('DARLAN', '(31) 96666-5555'),
       ('CARLOS', '(41) 93333-2222');
       
-- CONSULTA A TABELA DE CONTATOS
    SELECT * FROM TB_CONTATOS   

-- ALTERANDO A ESTRUTURA DE UMA TABELA
-- ATRAVES DO COMANDO ALTER TABLE

ALTER TABLE TB_CONTATOS
ADD COLUMN ativo INT DEFAULT 1;

INSERT INTO TB_CONTATOS (nome, telefone)
VALUES ('RICARDO', '(78) 95555-4444');


-- UTLIZANDO O ALIAS PARA APELIDO DE COLUNA
SELECT nome, telefone as celular FROM TB_CONTATOS;

-- CONSULTA A TABELA CONTATOS
SELECT * FROM TB_CONTATOS;

-- DESCRIÇÃO DA TABELA CONTATOS
DESCRIBE TB_CONTATOS;

-- ALTERANDO O NOME DE UMA COLUNA
ALTER TABLE TB_CONTATOS
CHANGE COLUMN telefone celular VARCHAR(20) NOT NULL;


-- DELETANDO/ EXCLUINDO UMA COLUNA DA TABELA
ALTER TABLE TB_CONTATOS
DROP COLUMN ativo;





