
-- T04301 - CRIANDO O BANCO DE DADOS

CREATE DATABASE DB_T04301_JESSE_ALVES;

CREATE DATABASE IF NOT EXISTS DB_T04301_JESSE_ALVES;

-- ACESSAR O BD
USE DB_T04301_JESSE_ALVES;
-- CRIAR A TABELA CLIENTES
CREATE TABLE TB_CLIENTES (
	id_cliente INT PRIMARY KEY,
    nome VARCHAR(250),
    idade INT
);

-- CONSULTANDO AS INFORMAÇÕES NA TABELA
SELECT * FROM TB_CLIENTES;

-- INSERIR REGISTROS NA TABELA CLIENTES
INSERT INTO TB_CLIENTES (id_cliente, nome, idade)
VALUES (1, 'JESSE' , 41);









