-- ACESSANDO O BD
USE DB_T04301_JESSE_ALVES;

-- CRIANDO A TABELA DE CONTA CLIENTE

CREATE TABLE TB_CONTA_CLIENTE (
    id_cliente INT AUTO_INCREMENT PRIMARY KEY,
    nome_cliente VARCHAR(100) NOT NULL,
    saldo DECIMAL(10, 2) NOT NULL
);


-- INSERINDO REGISTROS NA TEBELA CONTA CLIENTE
INSERT INTO TB_CONTA_CLIENTE (nome_cliente, saldo)
VALUES ('Fernanda', '1000.00'),
	   ('Gabriel', '800.00');
       
-- CONSULTAR A TEBELA CONTA CLIENTE
SELECT * FROM TB_CONTA_CLIENTE;   

-- USANDO COMANDOS - TCL
-- EXEMPLO 01 -> CREDITAR 300 NO SALDO DA FERNANDA    

-- INICIO DA TRANSAÇÃO
START TRANSACTION;

-- ATUALIZAR O SALDO DA FERNANDA
UPDATE TB_CONTA_CLIENTE
SET saldo = saldo + 300
WHERE id_cliente = 1;

-- CONFIRMAR A TRANSAÇÃO
COMMIT;

-- CONFIRMAR O SALDO DOS CLIENTE
SELECT * FROM TB_CONTA_CLIENTE;   

-- EXEMPLO 02 -> TENTATIVA DE CREDITAR 300 NO SALDO DO GRABRIEL
-- INICIO DA TRANSAÇÃO
START TRANSACTION;

-- ATUALIZAR O SALDO DO CLIENTE

-- EXEMPLO FEITO PARA CREDITAR O SALDO
UPDATE TB_CONTA_CLIENTE
SET saldo = saldo + 300
WHERE id_cliente = 2;

/* -- EXEMPLO FEITO PARA SUBTRAIR O SALDO
UPDATE TB_CONTA_CLIENTE
SET saldo = saldo - 300
WHERE id_cliente = 2;
*/

-- DESFAZER A TRANSAÇÃO
ROLLBACK;


-- EXEMPLO 03 -> CREDITO EM UMA CONTA E DEBITO EM OUTRA CONTA
START TRANSACTION;
-- 1 PASSO ->  ATUALIZAR O SALDO DO GABRIEL
UPDATE TB_CONTA_CLIENTE
SET saldo = saldo + 700
WHERE id_cliente = 2;

	SELECT * FROM TB_CONTA_CLIENTE; 
-- PONTO DE SALVAMENTO
SAVEPOINT PONTO_SALVE_1;

-- DEBITAR O SALDO DA FERNANDA 
UPDATE TB_CONTA_CLIENTE
SET saldo = saldo - 200
WHERE id_cliente = 1;

-- DESFAZ A AÇÃO DEBITO NA CONTA DA FERNANDA
ROLLBACK TO SAVEPOINT PONTO_SALVE_1;

-- ENCERRAR AS INFORMAÇÕES
COMMIT;

SELECT * FROM TB_CONTA_CLIENTE; 


