
USE DB_T04301_JESSE_ALVES


-- DIFERENÇA ENTRE DELETE E TRUNCATE TABLE
SELECT * FROM TB_CONTA_CLIENTE;

-- EXEMPLO DE DELETE 
START TRANSACTION;
-- ELIMINAR TODOS OS REGISTROS DA TABELA
DELETE FROM TB_CONTA_CLIENTE;
-- DEFAZ AÇÃO
ROLLBACK;


-- EXEMPLO DE TRUNCATE TABLE 
START TRANSACTION;
-- ELIMINAR TODOS OS REGISTROS DA TABELA
TRUNCATE TABLE TB_CONTA_CLIENTE;
-- TENTATIVA DEFAZER AÇÃO
ROLLBACK;


